name: news_app
description: "A new Flutter project for News from newsapi.org."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/icon/
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
